apiVersion: v1
entries:
  k8sdemo:
  - apiVersion: v2
    appVersion: "0.3"
    created: "2022-07-07T14:04:55.815993454Z"
    description: K8sDemo App Helm chart prepared by Sourish
    digest: bc10b761d3b1220bf58fed404c1d3d030e92bf8aff38306fdc7559e6a192e6f5
    name: k8sdemo
    type: application
    urls:
    - k8sdemo-0.1.0.tgz
    version: 0.1.0
  nginx:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-07T14:04:55.816924383Z"
    description: A Helm chart for Kubernetes
    digest: db1c7afbe153340fde914a7acb75ebb1788b27ca7d285646334c6d2ee15c824a
    name: nginx
    type: application
    urls:
    - nginx-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-07T14:04:55.815293131Z"
